from .avatar_options import AvatarOptions
from .economic_options import EconomicOptions
from .general_options import GeneralOptions
from .rock_paper_scissors_options import RockPaperScissorsOptions
from .user_profile_options import UserProfileOptions
from .waifu_pics_options import WaifuPicsOptions
