name: Version generator

on:
  push:
    branches:
      - main
      - 'develop/**'
  workflow_dispatch:
    branches:
      - main
      - 'develop/**'

jobs:
  run:
    name: Assign the latest version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Generate the version number
        run: generate_version.sh
      
      - name: Commit the changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Generate current version number'
          add: '*.py'
