name: Version generator

on:
  push:
    branches:
      - 'develop/**'
  workflow_dispatch:

jobs:
  run:
    name: Assign the latest version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate the version number
        run: python generate_version.py

      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Generate current version number'
          add: ['*.py', 'VERSION']
